version: '3'

services:
  api:
    build: ./api
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dataDB:/var/lib/mysql
volumes:
  dataDB:
