version: '3'

services:

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: cv_db
    volumes:
      - dataDB:/var/lib/mysql
volumes:
  dataDB:
